export const CountriesImages = {
  Bahrain: require("../assets/flags/bahrain_flag.png"),
  UAE: require("../assets/flags/abu_dhabi_flag.png"),
  Australia: require("../assets/flags/australia_flag.png"),
  Australian: require("../assets/flags/australia_flag.png"),
  Austria: require("../assets/flags/austria_flag.png"),
  Austrian: require("../assets/flags/austria_flag.png"),
  Azerbaijan: require("../assets/flags/azerbaijan_flag.png"),
  Belgium: require("../assets/flags/belgium_flag.png"),
  Brazil: require("../assets/flags/brazil_flag.png"),
  Canada: require("../assets/flags/canada_flag.png"),
  Canadian: require("../assets/flags/canada_flag.png"),
  "Great Britain": require("../assets/flags/great_britain_flag.png"),
  British: require("../assets/flags/great_britain_flag.png"),
  UK: require("../assets/flags/great_britain_flag.png"),
  French: require("../assets/flags/france_flag.png"),
  Thai: require("../assets/flags/thailand.png"),
  Finnish: require("../assets/flags/finland_flag.png"),
  Swiss: require("../assets/flags/swiss_flag.jpg"),
  Chinese: require("../assets/flags/china_flag.png"),
  German: require("../assets/flags/germany_flag.png"),
  Danish: require("../assets/flags/denmark_flag.png"),
  Hungary: require("../assets/flags/hungary_flag.png"),
  Italy: require("../assets/flags/italy_flag.png"),
  Italian: require("../assets/flags/italy_flag.png"),
  Japan: require("../assets/flags/japan_flag.png"),
  Japanese: require("../assets/flags/japan_flag.png"),
  Mexico: require("../assets/flags/mexico_flag.png"),
  Mexican: require("../assets/flags/mexico_flag.png"),
  Monaco: require("../assets/flags/monaco_flag.png"),
  Monegasque: require("../assets/flags/monaco_flag.png"),
  Netherlands: require("../assets/flags/netherlands_flag.png"),
  Dutch: require("../assets/flags/netherlands_flag.png"),
  Qatar: require("../assets/flags/qatar_flag.png"),
  "Saudi Arabia": require("../assets/flags/saudi_arabia_flag.png"),
  Singapore: require("../assets/flags/singapore_flag.png"),
  Spanish: require("../assets/flags/spain_flag.png"),
  Spain: require("../assets/flags/spain_flag.png"),
  "United States": require("../assets/flags/united_states_flag.png"),
  American: require("../assets/flags/united_states_flag.png"),
  USA: require("../assets/flags/united_states_flag.png")

//   "Great Britain": "https://i.ibb.co/XCXp0H7/great-britain-flag.png",
//   British: "https://i.ibb.co/XCXp0H7/great-britain-flag.png",
//   UK: "https://i.ibb.co/XCXp0H7/great-britain-flag.png",
// hungary: "https://i.ibb.co/smf7Cxh/hungary-flag.png",
// italy: "https://i.ibb.co/NpF38Cj/italy-flag.png",
// japan: "https://i.ibb.co/Ptr5CJ8/japan-flag.png",
// mexico: "https://i.ibb.co/jvZ23n4/mexico-flag.png",
// monaco: "https://i.ibb.co/VjppYVx/monaco-flag.png",
// netherlands: "https://i.ibb.co/ZLJPjP7/netherlands-flag.png",
// qatar: "https://i.ibb.co/wcN2NXN/qatar-flag.png",
// : "https://i.ibb.co/qkRPgFy/saudi-arabia-flag.png",
// singapore: "https://i.ibb.co/CtQS8ys/singapore-flag.png",
// spain: "https://i.ibb.co/rFkN2tZ/spain-flag.png",
// thailand: "https://i.ibb.co/y6PskMx/thailand.png",
// : "https://i.ibb.co/c3rH1pc/united-states-flag.png",
// : "https://i.ibb.co/q0NwQ79/abu-dhabi-flag.png",
// australia: "https://i.ibb.co/jJZZL4T/australia-flag.png",
// austria: "https://i.ibb.co/6mN5Rfd/austria-flag.png",
// azerbaijan: "https://i.ibb.co/9n9dQKY/azerbaijan-flag.png",
// bahrain: "https://i.ibb.co/BzN0byN/bahrain-flag.png",
// belgium: "https://i.ibb.co/3RMF6Kr/belgium-flag.png",
// brazil: "https://i.ibb.co/k0ZyrVS/brazil-flag.png",
// canada: "https://i.ibb.co/X7dXZk9/canada-flag.png",
// china: "https://i.ibb.co/ZG05VJB/china-flag.png",
// denmark: "https://i.ibb.co/7JXYxJc/denmark-flag.png",
// finland: "https://i.ibb.co/44S7QJ3/finland-flag.png",
// france: "https://i.ibb.co/0n0H7XY/france-flag.png",
// germany: "https://i.ibb.co/z5GJ2tM/germany-flag.png"
}
