export const CircuitsImages = {
  bahrain: require("../assets/circuits/bahrain.png"),
  jeddah: require("../assets/circuits/saudi_arabia.png"),
  albert_park: require("../assets/circuits/australia.png"),
  baku: require("../assets/circuits/azerbaijan.png"),
  miami: require("../assets/circuits/miami.png"),
  imola: require("../assets/circuits/emilia_romagna.png"),
  monaco: require("../assets/circuits/monaco.png"),
  catalunya: require("../assets/circuits/spain.png"),
  villeneuve: require("../assets/circuits/canada.png"),
  red_bull_ring: require("../assets/circuits/austria.png"),
  silverstone: require("../assets/circuits/great_britain.png"),
  hungaroring: require("../assets/circuits/hungary.png"),
  spa: require("../assets/circuits/belgium.png"),
  zandvoort: require("../assets/circuits/netherlands.png"),
  monza: require("../assets/circuits/italy.png"),
  marina_bay: require("../assets/circuits/singapore.png"),
  suzuka: require("../assets/circuits/japan.png"),
  losail: require("../assets/circuits/qatar.png"),
  americas: require("../assets/circuits/united_states.png"),
  rodriguez: require("../assets/circuits/mexico.png"),
  interlagos: require("../assets/circuits/brazil.png"),
  vegas: require("../assets/circuits/las_vegas.png"),
  yas_marina: require("../assets/circuits/abu_dhabi.png")
}
