export const CircuitsImages = {
  // bahrain: require("../assets/circuits/bahrain.png"),
  // jeddah: require("../assets/circuits/saudi_arabia.png"),
  // albert_park: require("../assets/circuits/australia.png"),
  // baku: require("../assets/circuits/azerbaijan.png"),
  // miami: require("../assets/circuits/miami.png"),
  // imola: require("../assets/circuits/emilia_romagna.png"),
  // monaco: require("../assets/circuits/monaco.png"),
  // catalunya: require("../assets/circuits/spain.png"),
  // villeneuve: require("../assets/circuits/canada.png"),
  // red_bull_ring: require("../assets/circuits/austria.png"),
  // silverstone: require("../assets/circuits/great_britain.png"),
  // hungaroring: require("../assets/circuits/hungary.png"),
  // spa: require("../assets/circuits/belgium.png"),
  // zandvoort: require("../assets/circuits/netherlands.png"),
  // monza: require("../assets/circuits/italy.png"),
  // marina_bay: require("../assets/circuits/singapore.png"),
  // suzuka: require("../assets/circuits/japan.png"),
  // losail: require("../assets/circuits/qatar.png"),
  // americas: require("../assets/circuits/united_states.png"),
  // rodriguez: require("../assets/circuits/mexico.png"),
  // interlagos: require("../assets/circuits/brazil.png"),
  // vegas: require("../assets/circuits/las_vegas.png"),
  // yas_marina: require("../assets/circuits/abu_dhabi.png")
  bahrain: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059870/f1-stats/circuits/bahrain_rj7qyx.png",
  jeddah: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059869/f1-stats/circuits/saudi_arabia_fywgan.png",
  albert_park: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059870/f1-stats/circuits/australia_ix3lrg.png",
  baku: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059870/f1-stats/circuits/azerbaijan_mbesgd.png",
  miami: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059869/f1-stats/circuits/miami_qhvhpo.png",
  imola: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059868/f1-stats/circuits/emilia_romagna_j8gpad.png",
  monaco: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059869/f1-stats/circuits/monaco_n4kcbf.png",
  catalunya: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059869/f1-stats/circuits/spain_oqjpkm.png",
  villeneuve: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059870/f1-stats/circuits/canada_ey2ks8.png",
  red_bull_ring: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059870/f1-stats/circuits/austria_evtk1x.png",
  silverstone: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059868/f1-stats/circuits/great_britain_pg0bsk.png",
  hungaroring: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059868/f1-stats/circuits/hungary_x4uyu4.png",
  spa: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059870/f1-stats/circuits/belgium_eg6owz.png",
  zandvoort: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059869/f1-stats/circuits/netherlands_muwz5a.png",
  monza: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059868/f1-stats/circuits/italy_kxmqw5.png",
  marina_bay: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059869/f1-stats/circuits/singapore_i9nzf4.png",
  suzuka: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059868/f1-stats/circuits/japan_xpflg6.png",
  losail: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059869/f1-stats/circuits/qatar_u749w1.png",
  americas: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059869/f1-stats/circuits/united_states_wyc5er.png",
  rodriguez: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059869/f1-stats/circuits/mexico_bakfqx.png",
  interlagos: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059870/f1-stats/circuits/brazil_ws2poj.png",
  vegas: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059868/f1-stats/circuits/las_vegas_cb6dja.png",
  yas_marina: "https://res.cloudinary.com/dvjbhwt2l/image/upload/v1680059870/f1-stats/circuits/abu_dhabi_oxg2oi.png"
}
